server:
  port: 8082

spring:
  application:
    name: course

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true

  jmx:
    enabled: false

  datasource:
    url: jdbc:mysql://localhost:3307/devdojo?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: felipe
  jackson:
    serialization:
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: true
    default-property-inclusion: NON_NULL

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true


jwt:
  config:
    type: signed

## spring actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
      base-path: "/admin/actuator"


